/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout-cancel'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as ApiWebhookStripeRouteImport } from './routes/api.webhook.stripe'
import { Route as ApiWebhookPaypalRouteImport } from './routes/api.webhook.paypal'
import { Route as ApiWebhookCreemRouteImport } from './routes/api.webhook.creem'
import { Route as ApiPaypalCheckoutRouteImport } from './routes/api.paypal.checkout'
import { Route as ApiCreemCheckoutRouteImport } from './routes/api.creem.checkout'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout-cancel',
  path: '/checkout-cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhookStripeRoute = ApiWebhookStripeRouteImport.update({
  id: '/api/webhook/stripe',
  path: '/api/webhook/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookPaypalRoute = ApiWebhookPaypalRouteImport.update({
  id: '/api/webhook/paypal',
  path: '/api/webhook/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookCreemRoute = ApiWebhookCreemRouteImport.update({
  id: '/api/webhook/creem',
  path: '/api/webhook/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaypalCheckoutRoute = ApiPaypalCheckoutRouteImport.update({
  id: '/api/paypal/checkout',
  path: '/api/paypal/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreemCheckoutRoute = ApiCreemCheckoutRouteImport.update({
  id: '/api/creem/checkout',
  path: '/api/creem/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/checkout-cancel': typeof CheckoutCancelRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/creem/checkout': typeof ApiCreemCheckoutRoute
  '/api/paypal/checkout': typeof ApiPaypalCheckoutRoute
  '/api/webhook/creem': typeof ApiWebhookCreemRoute
  '/api/webhook/paypal': typeof ApiWebhookPaypalRoute
  '/api/webhook/stripe': typeof ApiWebhookStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/checkout-cancel': typeof CheckoutCancelRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/creem/checkout': typeof ApiCreemCheckoutRoute
  '/api/paypal/checkout': typeof ApiPaypalCheckoutRoute
  '/api/webhook/creem': typeof ApiWebhookCreemRoute
  '/api/webhook/paypal': typeof ApiWebhookPaypalRoute
  '/api/webhook/stripe': typeof ApiWebhookStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth-callback': typeof AuthCallbackRoute
  '/blog': typeof BlogRoute
  '/checkout-cancel': typeof CheckoutCancelRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/api/creem/checkout': typeof ApiCreemCheckoutRoute
  '/api/paypal/checkout': typeof ApiPaypalCheckoutRoute
  '/api/webhook/creem': typeof ApiWebhookCreemRoute
  '/api/webhook/paypal': typeof ApiWebhookPaypalRoute
  '/api/webhook/stripe': typeof ApiWebhookStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth-callback'
    | '/blog'
    | '/checkout-cancel'
    | '/checkout-success'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/admin/payments'
    | '/admin/subscriptions'
    | '/api/creem/checkout'
    | '/api/paypal/checkout'
    | '/api/webhook/creem'
    | '/api/webhook/paypal'
    | '/api/webhook/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth-callback'
    | '/blog'
    | '/checkout-cancel'
    | '/checkout-success'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/admin/payments'
    | '/admin/subscriptions'
    | '/api/creem/checkout'
    | '/api/paypal/checkout'
    | '/api/webhook/creem'
    | '/api/webhook/paypal'
    | '/api/webhook/stripe'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth-callback'
    | '/blog'
    | '/checkout-cancel'
    | '/checkout-success'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/admin/payments'
    | '/admin/subscriptions'
    | '/api/creem/checkout'
    | '/api/paypal/checkout'
    | '/api/webhook/creem'
    | '/api/webhook/paypal'
    | '/api/webhook/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogRoute: typeof BlogRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ApiCreemCheckoutRoute: typeof ApiCreemCheckoutRoute
  ApiPaypalCheckoutRoute: typeof ApiPaypalCheckoutRoute
  ApiWebhookCreemRoute: typeof ApiWebhookCreemRoute
  ApiWebhookPaypalRoute: typeof ApiWebhookPaypalRoute
  ApiWebhookStripeRoute: typeof ApiWebhookStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-cancel': {
      id: '/checkout-cancel'
      path: '/checkout-cancel'
      fullPath: '/checkout-cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhook/stripe': {
      id: '/api/webhook/stripe'
      path: '/api/webhook/stripe'
      fullPath: '/api/webhook/stripe'
      preLoaderRoute: typeof ApiWebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/paypal': {
      id: '/api/webhook/paypal'
      path: '/api/webhook/paypal'
      fullPath: '/api/webhook/paypal'
      preLoaderRoute: typeof ApiWebhookPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/creem': {
      id: '/api/webhook/creem'
      path: '/api/webhook/creem'
      fullPath: '/api/webhook/creem'
      preLoaderRoute: typeof ApiWebhookCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paypal/checkout': {
      id: '/api/paypal/checkout'
      path: '/api/paypal/checkout'
      fullPath: '/api/paypal/checkout'
      preLoaderRoute: typeof ApiPaypalCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/creem/checkout': {
      id: '/api/creem/checkout'
      path: '/api/creem/checkout'
      fullPath: '/api/creem/checkout'
      preLoaderRoute: typeof ApiCreemCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogRoute: BlogRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ApiCreemCheckoutRoute: ApiCreemCheckoutRoute,
  ApiPaypalCheckoutRoute: ApiPaypalCheckoutRoute,
  ApiWebhookCreemRoute: ApiWebhookCreemRoute,
  ApiWebhookPaypalRoute: ApiWebhookPaypalRoute,
  ApiWebhookStripeRoute: ApiWebhookStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
